server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
  show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka